name: CI
on: push
jobs:
  ci-yo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test -- --watchAll=false
      - name: Build
        run: |
          npm run build && npm run build:website
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./playground/build
